dist: trusty
sudo: false
language: cpp

addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - g++-8

before_install:
        - pip install --user cpp-coveralls

script:
        - CXX=/usr/bin/g++-8 CC=/usr/bin/gcc-8 GCOV=/usr/bin/gcov-8 cmake -DCOVERAGE=1 -DBUILD_ON_TRAVIS=1 .
        - cmake --build .
        - ./data_structures_tests
        - ./algorithms_tests
        - ./asm_tests
        - ./interview_tests

after_success:
        - coveralls --gcov /usr/bin/gcov-8 --root . -E ".*gtest.*" -E ".*CMakeFiles.*"
